# Generated by Django 4.0.4 on 2022-05-16 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_rename_benficiary_account_number_transfer_beneficiary_account_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='transfer_pin',
            field=models.CharField(default=0, max_length=4),
            preserve_default=False,
        ),
    ]
