# Generated by Django 4.0.4 on 2022-05-16 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_transfer_transfer_pin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='transfer_pin',
            field=models.CharField(max_length=6),
        ),
    ]
