# Generated by Django 4.0.4 on 2022-05-16 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_alter_transfer_transfer_pin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfer',
            name='transfer_pin',
        ),
    ]
