# Generated by Django 4.0.4 on 2023-01-12 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_alter_transfer_iban'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='account_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='beneficiary_account_number',
            field=models.CharField(max_length=20),
        ),
    ]
