# Generated by Django 4.0.4 on 2022-06-09 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibanking', '0003_alter_bankinghistory_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankinghistory',
            name='balance',
            field=models.DecimalField(decimal_places=2, default='0.0', max_digits=10),
        ),
    ]
