# Generated by Django 4.0.4 on 2022-07-25 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibanking', '0004_bankinghistory_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankinghistory',
            name='balance',
        ),
        migrations.AlterField(
            model_name='bankinghistory',
            name='amount',
            field=models.DecimalField(decimal_places=2, default='0.0', max_digits=10),
        ),
    ]
