# Generated by Django 4.0.4 on 2022-07-25 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibanking', '0006_bankinghistory_amt_aft_charges'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankinghistory',
            name='amt_aft_charges',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
