# Generated by Django 4.0.4 on 2022-07-28 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibanking', '0008_alter_bankinghistory_amt_aft_charges'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankinghistory',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='bankinghistory',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='bankinghistory',
            name='amt_aft_charges',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
